### ISSUE TITLE
Instalation and fisrt use issues

### ISSUE THREAD

**Issue by fernandomayer** [alexander-pastukhov/bistablehistory#1]
Hi @alexander-pastukhov, 

I'm starting to review your package for JOSS (https://github.com/openjournals/joss-reviews/issues/3901) and when I try to install it, I get this output:

```r
> library("devtools")
Loading required package: usethis
> install_github("alexander-pastukhov/bistablehistory",dependencies=TRUE)
Downloading GitHub repo alexander-pastukhov/bistablehistory@HEAD
✔  checking for file ‘/tmp/RtmpXBmB2G/remotes22da80592c6/alexander-pastukhov-bistablehistory-4053d59/DESCRIPTION’ ...
─  preparing ‘bistablehistory’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
   Warning in system2(command, args, stdout = NULL, stderr = NULL, ...) :
     error in running command
─  installing the package to process help pages
```

The 9th line seems strange to me. Maybe there is something diferent in the `src` directory? After this, the package compiles and installs normally. However, when I try to run the first example in `README`, I get an error saying that the `fit_cumhist` could not be found:

```r
> library(bistablehistory)
> data(br_singleblock)
> gamma_fit <- fit_cumhist(br_singleblock,
                        state="State",
                        duration="Duration")
Error in fit_cumhist(br_singleblock, state = "State", duration = "Duration") : 
  could not find function "fit_cumhist"
```

It looks like `fit_cumhist` was not exported. I saw it has the `@export` tag, but it is not in the `NAMESPACE`. Maybe you need to update it?

This is my `sessionInfo()`

```
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS/LAPACK: /opt/intel/mkl/lib/intel64/libmkl_gf_lp64.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lattice_0.20-45

loaded via a namespace (and not attached):
[1] compiler_4.1.2 tools_4.1.2    grid_4.1.2    
```

**Comment by alexander-pastukhov** [comment]
Dear @fernandomayer, 

thank you and terribly sorry, I was so happy that the CRAN version works that I did not double check the developmental version. I've added information on installation from CRAN to README (`install.packages("bistablehistory")` that one definitely works and the installation is much quicker with precompiled binaries). For the developmental version the exports were indeed MIA somehow, not sure how that could have happened given that they are generated by roxygen2. I've re-roxygenized it, so the exports are there and package installs correctly and works. 

Line #9   `Warning in system2(command, args, stdout = NULL, stderr = NULL, ...) :     error in running command`
Cannot replicate it on Windows but it is looks like a part of the general package infrastructure.

**Comment by fernandomayer** [comment]
Thanks.

I tested both the CRAN and the Github versions and now both are working. 

Just a few additional comments:

- The line #9 warning is still there when installing from Github, but that didn't affect the installation. I suppose this is a minor issue, but maybe it could be addressed in the future. If it passed the CRAN checks, it possibly is an issue specific to my system.
- Precompiled binaries are available only for Windows. Any package installed from CRAN on Linux will be compiled from source anyway (unless you explicitly provide precompiled binaries for Linux, which is very uncommon - and I think it is even not recommended). This is not a problem *per se*, just to let you know.
- Maybe it would be useful to inform in `README` that the Github version in the `master` branch is the development version (it may not be obvious to everyone)

**Comment by alexander-pastukhov** [comment]
* line #9, no warnings or even notes on that, even during the official CRAN check (that tends to catch more things than one in devtools).
* Not sure whether I can do anything about this as this is on CRAN's side, I only submit source package (as recommended).
* Thank you, good point! Added this info to README.
